/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/REACTANIMATIONEXPORT.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.dance.play() 
  },)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorig1Hips} />
          <skinnedMesh name="Ch45" geometry={nodes.Ch45.geometry} material={materials.Ch45_Body} skeleton={nodes.Ch45.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/REACTANIMATIONEXPORT.glb')
