/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/room.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001" position={[9.33, -0.03, -0.28]} rotation={[Math.PI / 2, 0, -1.51]} scale={0.03}>
          <primitive object={nodes.mixamorig7Hips} />
          <skinnedMesh name="Ch08_Beard" geometry={nodes.Ch08_Beard.geometry} material={materials.Ch08_hair} skeleton={nodes.Ch08_Beard.skeleton} />
          <skinnedMesh name="Ch08_Body" geometry={nodes.Ch08_Body.geometry} material={materials.Ch08_body} skeleton={nodes.Ch08_Body.skeleton} />
          <skinnedMesh name="Ch08_Eyelashes" geometry={nodes.Ch08_Eyelashes.geometry} material={materials.Ch08_hair} skeleton={nodes.Ch08_Eyelashes.skeleton} />
          <skinnedMesh name="Ch08_Hair" geometry={nodes.Ch08_Hair.geometry} material={materials.Ch08_hair} skeleton={nodes.Ch08_Hair.skeleton} />
          <skinnedMesh name="Ch08_Hoodie" geometry={nodes.Ch08_Hoodie.geometry} material={materials.Ch08_body1} skeleton={nodes.Ch08_Hoodie.skeleton} />
          <skinnedMesh name="Ch08_Pants" geometry={nodes.Ch08_Pants.geometry} material={materials.Ch08_body1} skeleton={nodes.Ch08_Pants.skeleton} />
          <skinnedMesh name="Ch08_Sneakers" geometry={nodes.Ch08_Sneakers.geometry} material={materials.Ch08_body1} skeleton={nodes.Ch08_Sneakers.skeleton} />
        </group>
        <group name="Area" position={[-6.74, 9.6, -6.74]} rotation={[-0.96, Math.PI / 6, 0.62]} scale={[4.5, 1.51, 1.51]} />
        <group name="Area001" position={[14.73, 3.07, -7.72]} rotation={[-1.37, -0.13, -1.13]} scale={[5.44, 0.24, 2.26]} />
        <group name="Area002" position={[-5.81, 4.03, 10.61]} rotation={[-1.7, 0.17, 2.73]} scale={[5.71, 2.71, 3.02]} />
        <group name="Spot" position={[-3.23, 5.43, -0.76]} rotation={[-0.09, -0.06, -0.29]}>
          {/* <spotLight name="Spot_Orientation" intensity={150} angle={0.51} penumbra={0.3} decay={2} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 0, -1]} />
          </spotLight> */}
        </group>
        <group name="Armature" position={[0.05, 0.04, 2.04]} rotation={[1.55, -0.01, -3.14]} scale={0.02}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Ch21_Body" geometry={nodes.Ch21_Body.geometry} material={materials.Ch21_body} skeleton={nodes.Ch21_Body.skeleton} />
          <skinnedMesh name="Ch21_Eyelasshes" geometry={nodes.Ch21_Eyelasshes.geometry} material={materials.Ch21_hair} skeleton={nodes.Ch21_Eyelasshes.skeleton} />
          <skinnedMesh name="Ch21_Hair" geometry={nodes.Ch21_Hair.geometry} material={materials.Ch21_hair} skeleton={nodes.Ch21_Hair.skeleton} />
          <skinnedMesh name="Ch21_Pants" geometry={nodes.Ch21_Pants.geometry} material={materials.Ch21_body} skeleton={nodes.Ch21_Pants.skeleton} />
          <skinnedMesh name="Ch21_Shirt" geometry={nodes.Ch21_Shirt.geometry} material={materials.Ch21_body} skeleton={nodes.Ch21_Shirt.skeleton} />
          <skinnedMesh name="Ch21_Shoes" geometry={nodes.Ch21_Shoes.geometry} material={materials.Ch21_body} skeleton={nodes.Ch21_Shoes.skeleton} />
        </group>
        <group name="Area003" position={[-11.86, 23.86, -12.49]} rotation={[-0.96, Math.PI / 6, 0.62]} scale={[15.05, 5.06, 5.06]} />
        <group name="Spot001" position={[8.37, 5.43, -3.27]} rotation={[-2.17, -1.46, -2.45]}>
          {/* <spotLight name="Spot001_Orientation" intensity={150} angle={0.51} penumbra={0.3} decay={2} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 0, -1]} />
          </spotLight> */}
        </group>
        <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials.stick} position={[11.24, 2.1, -0.97]} rotation={[-0.87, -1.37, -2.46]} scale={[0.02, 0.19, 0.02]} />
        <mesh name="Chair" geometry={nodes.Chair.geometry} material={materials.Chair} position={[9.72, 0.85, -0.27]} rotation={[Math.PI, -0.03, Math.PI]} scale={[0.58, 0.12, 0.58]}>
          <mesh name="BezierCurve001" geometry={nodes.BezierCurve001.geometry} material={materials.Metal} position={[0, -1.45, -0.23]} rotation={[0, 1.54, 0]} scale={[0.85, 4.2, 0.85]} />
          <mesh name="Cube069" geometry={nodes.Cube069.geometry} material={materials.Chair} position={[1.15, 8.1, 0]} scale={[0.2, 6.09, 1.06]} />
          <group name="Cylinder004" position={[0, -1.02, 0]} scale={[0.23, 0.75, 0.23]}>
            <mesh name="Cylinder000" geometry={nodes.Cylinder000.geometry} material={materials['Steel Black Polished']} />
            <mesh name="Cylinder000_1" geometry={nodes.Cylinder000_1.geometry} material={materials['Steel White']} />
          </group>
        </mesh>
        <mesh name="Desk_Plane005" geometry={nodes.Desk_Plane005.geometry} material={materials['Material.019']} position={[10.59, -0.19, -0.65]} rotation={[Math.PI / 2, 0, 0]} scale={0.49} />
        <group name="indoor_plant_02" position={[8.17, -0.09, -3.13]} rotation={[Math.PI / 2, 0, -0.11]} scale={0.4}>
          <mesh name="indoor_plant_02_1" geometry={nodes.indoor_plant_02_1.geometry} material={materials['IDP_root.001']} />
          <mesh name="indoor_plant_02_2" geometry={nodes.indoor_plant_02_2.geometry} material={materials['IDP_root_indoor_plant_2_NOR.jpg']} />
          <mesh name="indoor_plant_02_3" geometry={nodes.indoor_plant_02_3.geometry} material={materials['IDP_ground.001']} />
          <mesh name="indoor_plant_02_4" geometry={nodes.indoor_plant_02_4.geometry} material={materials['IDP_leaves.001']} />
          <mesh name="indoor_plant_02_5" geometry={nodes.indoor_plant_02_5.geometry} material={materials['IDP_Pot.001']} />
        </group>
        <mesh name="Цилиндр001" geometry={nodes.Цилиндр001.geometry} material={materials['Материал.001']} position={[11.34, 1.94, 0.95]} scale={0.09}>
          <group name="Цилиндр" position={[0, -1.38, 0]} scale={[1.15, 0.46, 1.15]}>
            <mesh name="Цилиндр_1" geometry={nodes.Цилиндр_1.geometry} material={materials['Материал.002']} />
            <mesh name="Цилиндр_2" geometry={nodes.Цилиндр_2.geometry} material={materials['Материал.003']} />
          </group>
        </mesh>
        <group name="Plane" position={[0, -0.11, 0]} scale={[4, 4.39, 4]}>
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.wall} />
          <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials.floor} />
          <mesh name="Cube004_3" geometry={nodes.Cube004_3.geometry} material={materials['Material.010']} position={[-0.06, 0.2, -0.83]} rotation={[0, 0.2, -Math.PI]} scale={0} />
          <group name="Cube005" position={[-0.08, 0.27, -0.84]} rotation={[1.43, 0.03, 2.94]} scale={[0.11, 0, 0.09]}>
            <mesh name="Cube009_1" geometry={nodes.Cube009_1.geometry} material={materials['Material.040']} />
            <mesh name="Cube009_2" geometry={nodes.Cube009_2.geometry} material={materials['Material.011']} />
            <mesh name="Cube009_3" geometry={nodes.Cube009_3.geometry} material={materials['Material.012']} />
          </group>
          <group name="Cube006_1" position={[-0.08, 0.27, -0.84]} rotation={[1.43, 0.03, 2.94]} scale={[0.11, 0, 0.09]}>
            <mesh name="Cube008_1" geometry={nodes.Cube008_1.geometry} material={materials['Material.040']} />
            <mesh name="Cube008_2" geometry={nodes.Cube008_2.geometry} material={materials['Material.041']} />
            <mesh name="Cube008_3" geometry={nodes.Cube008_3.geometry} material={materials['Material.018']} />
          </group>
          <group name="Cube007" position={[-0.06, 0.2, -0.77]} rotation={[0, 0.2, 0]} scale={[0.01, 0, 0.01]}>
            <mesh name="Cube010_1" geometry={nodes.Cube010_1.geometry} material={materials['Material.013']} />
            <mesh name="Cube010_2" geometry={nodes.Cube010_2.geometry} material={materials['Material.014']} />
          </group>
          <group name="Cube008" position={[-0.04, 0.2, -0.73]} rotation={[Math.PI, -0.2, Math.PI]} scale={[0.11, 0, 0.1]}>
            <mesh name="Cube011_1" geometry={nodes.Cube011_1.geometry} material={materials['Material.043']} />
            <mesh name="Cube011_2" geometry={nodes.Cube011_2.geometry} material={materials['Material.044']} />
            <mesh name="Cube011_3" geometry={nodes.Cube011_3.geometry} material={materials['Material.015']} />
          </group>
          <mesh name="Cube035" geometry={nodes.Cube035.geometry} material={materials['Material.036']} position={[-0.04, 0.2, -0.73]} rotation={[Math.PI, -0.2, Math.PI]} scale={[0.11, 0, 0.1]} />
        </group>
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.sofa} position={[0.02, 0.19, 2.19]} rotation={[-Math.PI, 0, -Math.PI]} scale={[2.96, 1, 0.93]}>
          <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials.metal} position={[0, 0.18, 0]} scale={[0.34, 1, 1.07]} />
          <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials.sofa} position={[0.44, 0.38, 0.16]} scale={[0.43, 1, 0.76]} />
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.sofa} position={[-0.43, 0.38, 0.16]} scale={[0.43, 1, 0.76]} />
          <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials.sofa} position={[0.68, 1.25, -0.68]} rotation={[1.53, 0, 0]} scale={[0.34, 0.58, 0.49]} />
          <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials.sofa} position={[0, 1.25, -0.68]} rotation={[1.53, 0, 0]} scale={[0.34, 0.58, 0.49]} />
          <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials.sofa} position={[-0.69, 1.25, -0.68]} rotation={[1.53, 0, 0]} scale={[0.34, 0.58, 0.49]} />
          {/* <mesh name="Plane007_1" geometry={nodes.Plane007_1.geometry} material={materials.sofa} position={[0.89, 0.83, 0.35]} rotation={[0, 1.57, 0]} scale={[0.67, 0.32, 0.12]} /> */}
          <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials.sofa} position={[-0.9, 0.83, 0.35]} rotation={[0, 1.57, 0]} scale={[0.67, 0.32, 0.12]} />
        </mesh>
        <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials.wood} position={[-0.06, 0.01, -3.32]} scale={[2.64, 1, 0.53]}>
          <mesh name="Plane011_2" geometry={nodes.Plane011_2.geometry} material={materials.metal} position={[-0.01, 0.71, 0.02]} scale={[0.03, 0.09, 0.17]} />
        </mesh>
        <group name="loopiridecent" position={[-4, 2.79, -0.63]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.87}>
          <mesh name="loopiridecent_1" geometry={nodes.loopiridecent_1.geometry} material={materials.loopiridecent} />
          <mesh name="loopiridecent_2" geometry={nodes.loopiridecent_2.geometry} material={materials['Material.017']} />
        </group>
        <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials.BH} position={[0, -0.48, 0]} scale={[27.29, 12.06, 29.32]} />
        <group name="Plane013" position={[2.18, 0.73, -3.03]} rotation={[0, 0.48, 0]} scale={[0.17, 0.26, 0.26]}>
          <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials.white} />
          <mesh name="Plane011_1" geometry={nodes.Plane011_1.geometry} material={materials['book.003']} />
        </group>
        <group name="Plane014" position={[-2.35, 0.07, -3.03]} rotation={[0, 0.48, 0]} scale={[0.17, 0.18, 0.26]}>
          <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials.white} />
          <mesh name="Plane011_1" geometry={nodes.Plane011_1.geometry} material={materials['book.003']} />
        </group>
        <group name="Plane015" position={[-2.35, 0.12, -3.03]} rotation={[0, 0.13, 0]} scale={[0.17, 0.27, 0.26]}>
          <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials.white} />
          <mesh name="Plane011_1" geometry={nodes.Plane011_1.geometry} material={materials['book.003']} />
        </group>
        <group name="Plane016" position={[-2.07, 0.16, -3.03]} rotation={[0, 0, -0.41]} scale={[0.17, 0.22, 0.26]}>
          <mesh name="Plane012_1" geometry={nodes.Plane012_1.geometry} material={materials.white} />
          <mesh name="Plane012_2" geometry={nodes.Plane012_2.geometry} material={materials['book.001']} />
        </group>
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.007']} position={[-3.27, 1.89, -3.44]} rotation={[0, -Math.PI / 2, 0]} scale={[0.53, 1.89, 0.38]}>
          <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.005']} position={[0.15, 0.02, 0]} scale={[0.96, 0.91, 0.96]} />
          <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials['Material.002']} position={[1.1, -0.04, -0.56]} rotation={[0, 0, -Math.PI / 2]} scale={[0.11, 0.96, 0.31]} />
          <group name="SketchUp001" position={[1, 0.09, 0.08]} rotation={[0, 0, -Math.PI / 2]} scale={0}>
            <mesh name="ID10" geometry={nodes.ID10.geometry} material={materials.material} />
            <mesh name="ID10_1" geometry={nodes.ID10_1.geometry} material={materials['Material.004']} />
          </group>
          <mesh name="SketchUp004" geometry={nodes.SketchUp004.geometry} material={materials.material} position={[0.87, -0.19, 0.08]} rotation={[0, 0, -Math.PI / 2]} scale={[0, 0.01, 0.01]} />
          <group name="SketchUp006" position={[0.86, -0.19, 0.12]} rotation={[0, 0, -Math.PI / 2]} scale={[0, 0.01, 0.01]}>
            <mesh name="ID10001" geometry={nodes.ID10001.geometry} material={materials.material} />
            <mesh name="ID10001_1" geometry={nodes.ID10001_1.geometry} material={materials['Material.004']} />
          </group>
          <group name="Torus" position={[1.12, 0.35, -0.01]} rotation={[0, 0, -Math.PI / 2]} scale={[0.03, 0.12, 0.17]}>
            <mesh name="Torus_1" geometry={nodes.Torus_1.geometry} material={materials['Material.003']} />
            <mesh name="Torus_2" geometry={nodes.Torus_2.geometry} material={materials['Material.008']} />
            <mesh name="Torus_3" geometry={nodes.Torus_3.geometry} material={materials['Material.009']} />
          </group>
        </mesh>
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.007']} position={[3.26, 1.89, -3.44]} rotation={[0, -Math.PI / 2, 0]} scale={[0.53, 1.89, 0.38]}>
          <mesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials['Material.005']} position={[0.15, 0.02, 0]} scale={[0.96, 0.91, 0.96]} />
          <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials['Material.002']} position={[1.1, -0.04, -0.56]} rotation={[0, 0, -Math.PI / 2]} scale={[0.11, 0.96, 0.31]} />
          <group name="SketchUp002" position={[1, 0.09, 0.08]} rotation={[0, 0, -Math.PI / 2]} scale={0}>
            <mesh name="ID10004" geometry={nodes.ID10004.geometry} material={materials.material} />
            <mesh name="ID10004_1" geometry={nodes.ID10004_1.geometry} material={materials['Material.004']} />
          </group>
          <mesh name="SketchUp003" geometry={nodes.SketchUp003.geometry} material={materials.material} position={[0.87, -0.19, 0.08]} rotation={[0, 0, -Math.PI / 2]} scale={[0, 0.01, 0.01]} />
          <group name="SketchUp005" position={[0.86, -0.19, 0.12]} rotation={[0, 0, -Math.PI / 2]} scale={[0, 0.01, 0.01]}>
            <mesh name="ID10005" geometry={nodes.ID10005.geometry} material={materials.material} />
            <mesh name="ID10005_1" geometry={nodes.ID10005_1.geometry} material={materials['Material.004']} />
          </group>
          <group name="Torus001" position={[1.12, 0.35, -0.01]} rotation={[0, 0, -Math.PI / 2]} scale={[0.03, 0.12, 0.17]}>
            <mesh name="Torus002" geometry={nodes.Torus002.geometry} material={materials['Material.003']} />
            <mesh name="Torus002_1" geometry={nodes.Torus002_1.geometry} material={materials['Material.008']} />
            <mesh name="Torus002_2" geometry={nodes.Torus002_2.geometry} material={materials['Material.009']} />
          </group>
        </mesh>
        <group name="Plane019" position={[8.28, -0.11, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[4, 4.39, 4]}>
          <mesh name="Plane009_1" geometry={nodes.Plane009_1.geometry} material={materials.wall} />
          <mesh name="Plane009_2" geometry={nodes.Plane009_2.geometry} material={materials.floor} />
        </group>
        <group name="Plane020" position={[8.26, -0.11, 8.28]} rotation={[Math.PI, 0, Math.PI]} scale={[4, 4.39, 4]}>
          <mesh name="Plane015_1" geometry={nodes.Plane015_1.geometry} material={materials.wall} />
          <mesh name="Plane015_2" geometry={nodes.Plane015_2.geometry} material={materials.floor} />
        </group>
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['Material.010']} position={[11.08, 1.79, -0.31]} rotation={[0, -1.53, 3.14]} scale={[-0.02, -0.01, -0.01]} />
        <group name="Cube010" position={[11.17, 2.14, -0.37]} rotation={[1.57, -0.14, -1.61]} scale={[0.49, 0.01, 0.45]}>
          <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Material.040']} />
          <mesh name="Cube004_1" geometry={nodes.Cube004_1.geometry} material={materials['Material.011']} />
          <mesh name="Cube004_2" geometry={nodes.Cube004_2.geometry} material={materials['Material.012']} />
        </group>
        <group name="Cube011" position={[11.17, 2.14, -0.37]} rotation={[1.57, -0.14, -1.61]} scale={[0.49, 0.01, 0.45]}>
          <mesh name="Cube012_1" geometry={nodes.Cube012_1.geometry} material={materials['Material.040']} />
          <mesh name="Cube012_2" geometry={nodes.Cube012_2.geometry} material={materials['Material.041']} />
          <mesh name="Cube012_3" geometry={nodes.Cube012_3.geometry} material={materials['Material.042']} />
        </group>
        <group name="Cube012" position={[10.86, 1.8, -0.36]} rotation={[0, -1.53, 0]} scale={[0.03, 0, 0.03]}>
          <mesh name="Cube013_1" geometry={nodes.Cube013_1.geometry} material={materials['Material.013']} />
          <mesh name="Cube013_2" geometry={nodes.Cube013_2.geometry} material={materials['Material.014']} />
        </group>
        <group name="Cube013" position={[10.67, 1.79, -0.31]} rotation={[-Math.PI, 1.53, -Math.PI]} scale={[0.49, 0.01, 0.45]}>
          <mesh name="Cube014_1" geometry={nodes.Cube014_1.geometry} material={materials['Material.043']} />
          <mesh name="Cube014_2" geometry={nodes.Cube014_2.geometry} material={materials['Material.044']} />
          <mesh name="Cube014_3" geometry={nodes.Cube014_3.geometry} material={materials['Material.015']} />
        </group>
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['Material.036']} position={[10.67, 1.79, -0.31]} rotation={[-Math.PI, 1.53, -Math.PI]} scale={[0.49, 0.01, 0.45]} />
        <group name="Plane024" position={[11.2, 2.34, -1.22]} rotation={[-0.91, -1.45, -2.49]} scale={[0.23, 0.23, 0.25]}>
          <mesh name="Plane019_1" geometry={nodes.Plane019_1.geometry} material={materials['Material.001']} />
          <mesh name="Plane019_2" geometry={nodes.Plane019_2.geometry} material={materials['tv.002']} />
        </group>
        <group name="Plane021" position={[12.23, 3.97, -0.02]} rotation={[0, -Math.PI / 2, 0]} scale={[0.7, 0.79, 0.84]}>
          <mesh name="Plane020_1" geometry={nodes.Plane020_1.geometry} material={materials['Material.001']} />
          <mesh name="Plane020_2" geometry={nodes.Plane020_2.geometry} material={materials['Material.042']} />
        </group>
        <group name="loopiridecent001" position={[8.24, 2.79, -4.03]} rotation={[Math.PI / 2, 0, 0]} scale={2.87}>
          <mesh name="loopiridecent001_1" geometry={nodes.loopiridecent001_1.geometry} material={materials['loopiridecent.001']} />
          <mesh name="loopiridecent001_2" geometry={nodes.loopiridecent001_2.geometry} material={materials['Material.017']} />
        </group>
        <group name="Plane009">
          <mesh name="Plane006_1" geometry={nodes.Plane006_1.geometry} material={materials['Material.001']} morphTargetDictionary={nodes.Plane006_1.morphTargetDictionary} morphTargetInfluences={nodes.Plane006_1.morphTargetInfluences} />
          <mesh name="Plane006_2" geometry={nodes.Plane006_2.geometry} material={materials.tv} morphTargetDictionary={nodes.Plane006_2.morphTargetDictionary} morphTargetInfluences={nodes.Plane006_2.morphTargetInfluences} />
          <mesh name="Plane006_3" geometry={nodes.Plane006_3.geometry} material={materials.BACKLIGHT} morphTargetDictionary={nodes.Plane006_3.morphTargetDictionary} morphTargetInfluences={nodes.Plane006_3.morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/room.glb')
